name: 'PR: Build, Release & Deploy'
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - '.github/**'
    types: [opened, synchronize, reopened,closed]
    branches:
    - master
    - main
    - stage

permissions:
  contents: write      

jobs:
  build:
   name: Build NestJS App
   uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Build-Test.yml@main
   with:
      platform: "node"
      command: "npm install && npm run build"
      
  create_release:
    if: github.event.pull_request.merged == true
    needs: build
    name: Create Tag and Release
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Create-Tag-Release.yml@main
    with:
     source_branch: ${{ github.base_ref }}
  
  gcp_deploy:
    if: github.event.pull_request.merged == true
    needs: create_release
    name: Trigger Deploy to GCP App Engine 
    uses: nabarun-ngo/ngo-nabarun-templates/.github/workflows/Trigger-Workflow.yml@main    
    with:
      repository: 'nabarun-ngo/ngo-nabarun-ops' 
      event_type: Trigger-DeployBE-Sync-Test
      input_json: |-
          {
            "be_deploy_v2": true ,
            "be_tag_name": "${{ needs.create_release.outputs.tag_name }}",
            "target_env": "${{ github.base_ref == 'main' && 'prod' || 'stage' }}",
            "auth0_sync" : ${{ contains(join(fromJSON(toJSON(github.event.pull_request.labels)).name, ','),'auth0') }},
            "run_smoke_test" : true ,
            "pr_number": "PR#${{github.event.pull_request.number}}"
          } 
    secrets:
      token: ${{ secrets.PAT }}
